-- 내장함수
SELECT UPPER(ENAME) FROM EMP

SELECT LENGTH(ENAME) FROM EMP

SELECT SUBSTR(ENAME,2) FROM EMP --두번째 글자부터 끝까지

SELECT SUBSTR(ENAME,1,2) FROM EMP --첫 두글자 

SELECT SUBSTR(ENAME,-2) FROM EMP --마지막 두글자

SELECT REPLACE(ENAME,'S','Z') FROM EMP

SELECT CONCAT (EMPNO,ENAME) FROM EMP

SELECT EMPNO||':'|| ENAME AS RESULT FROM EMP

SELECT TRIM(ENAME) FROM EMP

UPDATE EMP SET COMM = 0 WHERE COMM IS NULL

SELECT SAL+COMM AS TOTAL FROM EMP 

-- 문자함수, 숫자함수 정리 문제
SELECT * FROM EMP

SELECT LENGTH(ENAME) FROM EMP

SELECT LENGTH(ENAME) FROM EMP WHERE JOB = 'MANAGER'

SELECT ENAME, JOB FROM EMP WHERE COMM IS NULL

SELECT HIREDATE FROM EMP WHERE COMM IS NOT NULL

SELECT SUBSTR(ENAME,2) FROM EMP 

SELECT SUBSTR(JOB,1, 3) FROM EMP 

SELECT REPLACE (ENAME, 'K','P') FROM EMP

SELECT EMPNO || '번은 ' || ENAME || '입니다.' FROM EMP

SELECT HIREDATE,
TO_CHAR(HIREDATE , 'MM') AS MM, TO_CHAR(SYSDATE,'DAY') AS DAY 
FROM EMP

SELECT JOB,
CASE JOB
	WHEN 'MANAGER' THEN 'LEVEL1'
	WHEN 'SALESMAN' THEN 'LEVEL2'
	ELSE 'LEVEL3'
END AS LEVEL_RESULT
FROM EMP
	

-------------------------
-- 집계함수

SELECT COUNT(*) FROM EMP

SELECT COUNT(SAL), SUM(SAL), AVG(SAL), MIN(SAL), MAX(SAL)  
FROM EMP 
WHERE JOB = 'SALESMAN'

SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)), MIN(SAL), MAX(SAL)  
FROM EMP 
GROUP BY JOB

SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)), MIN(SAL), MAX(SAL)  
FROM EMP 
GROUP BY JOB
ORDER BY JOB DESC 

SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)), MIN(SAL), MAX(SAL)  
FROM EMP 
GROUP BY JOB
HAVING COUNT(SAL) >= 4 -- 그룹을 지어서 검색 후, 필터링을 하고자 하는 경우
ORDER BY JOB DESC -- 이미 모든 검색이 다 끝난 후, 그 결과를 정력하고자 하는 경우, 맨 끝

-- 집계/그룹함수 정리 문제
SELECT COUNT(*) FROM EMP

SELECT COUNT(*) FROM EMP WHERE DEPTNO = 20 OR MGR <= 7700

SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20

SELECT MIN(SAL), MAX(SAL), SUM(SAL) FROM EMP

SELECT DEPTNO, ROUND(AVG(SAL))
FROM EMP
GROUP BY DEPTNO 

SELECT DEPTNO, SUM(SAL)
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO

SELECT DEPTNO, ROUND(AVG(SAL))
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO DESC

SELECT COUNT(*), ROUND(AVG(SAL)) FROM EMP WHERE JOB = 'MANAGER'

SELECT COUNT(*) FROM EMP WHERE ENAME LIKE '%S%'

SELECT COUNT(*) 
FROM EMP 
WHERE SAL >= 3000 AND COMM IS NOT NULL
ORDER BY SAL DESC 

-- JOIN: 왜 하는가? 검색을 하고 싶은데 항목들이 여러개의 테이블에 흩어져있는 경우
-- 테이블을 모아서 (합해서) 검색

SELECT *
FROM "MEMBER" m ,BBS b 
WHERE m.ID = b.WRITER 

SELECT B.NO,B.TITLE,NAME,B.WRITER
FROM "MEMBER" m ,BBS b 
WHERE m.ID = b.WRITER 

-- INNER JOIN: 테이블 간 공통된 값만 추출
-- EMP테이블과 DEPT테이블을 조인하세요.
-- 하나의 컬럼이상이 동일한 컬럼이 있어야 함.
-- EMPNO, ENAME, JOB, DEPTNO, LOC 컬럼 검색
-- 조인 조건: DEPTNO
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.LOC
FROM EMP e , DEPT d 
WHERE E.DEPTNO = D.DEPTNO 

SELECT *
FROM "MEMBER" m ,BBS b 
WHERE m.ID = b.WRITER

SELECT *
FROM "MEMBER" m
LEFT OUTER JOIN BBS b
ON (m.ID = b.WRITER) 

SELECT *
FROM "MEMBER" m
RIGHT OUTER JOIN BBS b
ON (m.ID = b.WRITER) 

-- LEFT/RIGHT OUTER JOIN 
SELECT *
FROM EMP e 
LEFT OUTER JOIN DEPT d 
ON (E.DEPTNO = D.DEPTNO)

SELECT *
FROM EMP e 
RIGHT OUTER JOIN DEPT d 
ON (E.DEPTNO = D.DEPTNO)


CREATE TABLE COMPANY (
	ID VARCHAR2(200) PRIMARY KEY,
	NAME VARCHAR2(200),
	TEL VARCHAR2(200),
	ADDR VARCHAR2(200)
)

INSERT INTO COMPANY VALUES ('c100', 'good', 'seoul', '011')

INSERT INTO COMPANY VALUES ('c200', 'soso', 'paris', '012')

INSERT INTO COMPANY VALUES ('c300', 'bobo', 'roma', '013')

INSERT INTO COMPANY VALUES ('c400', 'dodo', 'busan', '014')

SELECT * FROM COMPANY

SELECT p.NAME , p.CONTENT, p.PRICE , c.ID , c.ADDR  
FROM PRODUCT p, COMPANY c 
WHERE p.COMPANY = c.ID 

SELECT *
FROM PRODUCT p
LEFT OUTER JOIN COMPANY c
ON (p.COMPANY = c.ID) 

SELECT *
FROM PRODUCT p
RIGHT OUTER JOIN COMPANY c
ON (p.COMPANY = c.ID) 








