CREATE TABLE "HR".SUBJECT 
(	"강좌이름" VARCHAR2(100), 
	"강의실" VARCHAR2(100), 
	 CONSTRAINT "SUBJECT_PK" PRIMARY KEY ("강좌이름")
)

CREATE TABLE "HR".DEPARTMENT
(	"학과" VARCHAR2(100) PRIMARY KEY, 
	"학과사무실" VARCHAR2(100)
)

CREATE TABLE "HR".STUDENT
(	"학생번호" NUMBER(38,0) PRIMARY KEY, 
	"학생이름" VARCHAR2(100),
	"주소" VARCHAR2(100),
	"학과" VARCHAR2(100),
	CONSTRAINT "FK_STUDENT" FOREIGN KEY ("학과")
	  REFERENCES "HR".DEPARTMENT ("학과")
)

CREATE TABLE "HR".RECORD
(	"학생번호" NUMBER(38,0), 
	"강좌이름" VARCHAR2(100),
	"성적" VARCHAR2(100),
	CONSTRAINT "FK_RECORD1" FOREIGN KEY ("학생번호")
	  REFERENCES "HR".STUDENT ("학생번호"),
	CONSTRAINT "FK_RECORD2" FOREIGN KEY ("강좌이름")
	  REFERENCES "HR".SUBJECT ("강좌이름")
)

INSERT INTO SUBJECT VALUES ('자바', '103')

INSERT INTO "RECORD"  VALUES (1, '자바', 'B')

UPDATE "RECORD"  SET 성적 = 'C' WHERE 학생번호 = 2 AND 강좌이름 = '인공지능';


SELECT *
FROM "RECORD" r, SUBJECT s 
WHERE r.강좌이름  = s.강좌이름 

SELECT r.학생번호, r.강좌이름, s.강의실 
FROM "RECORD" r
INNER JOIN SUBJECT s 
ON (r.강좌이름  = s.강좌이름) 

SELECT *
FROM "RECORD" r
INNER JOIN STUDENT s
ON (r.학생번호 = s.학생번호) 

SELECT * 
FROM STUDENT 
WHERE 학생번호 
IN (SELECT 학생번호 FROM "RECORD" WHERE 성적 = 'A')

SELECT *
FROM "RECORD"
WHERE 강좌이름 = (SELECT 강좌이름 FROM SUBJECT WHERE 강의실 = '101')

CREATE TABLE "HR".VIDEO 
(	"제목" VARCHAR2(100), 
	"채널명" VARCHAR2(100),
	"조회수" NUMBER(38,0),
	"카테고리" VARCHAR2(100),
	 CONSTRAINT "VIDEO_PK" PRIMARY KEY ("제목"),
	 CONSTRAINT "VIDEO_FK" FOREIGN KEY ("채널명")
	  REFERENCES "HR".CHANNEL ("채널명")
)

CREATE TABLE "HR".CHANNEL
(	"채널명" VARCHAR2(100), 
	"구독자수" NUMBER(38,0),
	"동영상수" NUMBER(38,0),
	 CONSTRAINT "CHANNEL_PK" PRIMARY KEY ("채널명")
)

CREATE TABLE "HR". YOUTUBE_MEMBER
(	"이름" VARCHAR2(100), 
	"이메일" VARCHAR2(100),
	"가입일" DATE,
	"구독채널" VARCHAR2(100),
	 CONSTRAINT "YOUTUBE_MEMBER_PK" PRIMARY KEY ("이메일"),
	 CONSTRAINT "YOUTUBE_MEMBER_FK" FOREIGN KEY ("구독채널")
	  REFERENCES "HR".CHANNEL ("채널명")
)

INSERT INTO CHANNEL VALUES ('뜬뜬', 0, 2)

UPDATE YOUTUBE_MEMBER SET 구독채널 = '옛능' WHERE 이름 = '박지성'

SELECT *
FROM YOUTUBE_MEMBER ym 
INNER JOIN CHANNEL c 
ON (ym.구독채널  = c.채널명) 

SELECT *
FROM VIDEO v 
INNER JOIN CHANNEL c 
ON (v.채널명 = c.채널명) 







