CREATE TABLE "HR"."NOTICE" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
   -- 추천게시판(recommend)
   -- re_no 숫자
   -- title,content, writer 문자
   
   CREATE TABLE "HR"."RECOMMEND"
   (
   		"RE_NO" NUMBER(38,0),
   		"TITLE" VARCHAR2(100),
   		"CONTENTS" VARCHAR2(100),
   		"WRITER" VARCHAR2(100)
   )
   
   DROP TABLE RECOMMEND -- 테이블 통채로 던져버림.
   
   ALTER TABLE HR.RECOMMEND DROP COLUMN VIEWCOUNT;
   
   CREATE TABLE "HR"."RECOMMEND"
   (
   		"RE_NO" NUMBER(38,0),
   		"TITLE" VARCHAR2(100),
   		"CONTENTS" VARCHAR2(100),
   		"WRITER" VARCHAR2(100)
   )
   
   CREATE TABLE "HR"."BOARD2" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )

ALTER TABLE HR.BOARD2 ADD TEST VARCHAR2(100) NULL;

ALTER TABLE HR.BOARD2 ADD TEST2 VARCHAR2(100) NULL;

ALTER TABLE HR.BOARD2 ADD TEST3 VARCHAR2(100) NULL;

ALTER TABLE HR.BOARD2 DROP COLUMN TEST;

ALTER TABLE HR.BOARD2 DROP COLUMN TEST2;

ALTER TABLE HR.BOARD2 DROP COLUMN TEST3;

ALTER TABLE HR.BOARD2 MODIFY WRITER VARCHAR2(300);


-- DCL : DB 관리/제어해주는 문법(계정생성, 계정권한부여, 백업, 복구)

CREATE USER apple IDENTIFIED BY a1234;

GRANT CONNECT, resource, dba TO apple -- 기본적인 권한 부여

CREATE TABLE "HR"."MEMBER" 
   (	"ID" VARCHAR2(100) PRIMARY KEY, 
	"PW" VARCHAR2(100), 
	"NAME" VARCHAR2(100), 
	"TEL" VARCHAR2(100)
   )

INSERT INTO "MEMBER" VALUES ('100','100','park','011');

INSERT INTO "MEMBER" VALUES ('200','200','park','011');

INSERT INTO "MEMBER" VALUES ('300','300','park','011');

SELECT * FROM "MEMBER";

SELECT * FROM "MEMBER" WHERE ID = '100'; -- id가 100인 모든 컬럼

SELECT name AS 이름, TEL FROM "MEMBER" WHERE ID = '100';

SELECT tel FROM "MEMBER" WHERE NAME = 'park';

SELECT * FROM "MEMBER" WHERE ID ='100' AND PW = '100';

SELECT * FROM "MEMBER" WHERE ID ='100' or ID = '200';

UPDATE "MEMBER" SET NAME = 'kim' WHERE ID = '100';

UPDATE "MEMBER" SET NAME = 'lee' WHERE ID = '200';

UPDATE "MEMBER" SET NAME = 'yoon' WHERE ID = '300';

UPDATE "MEMBER" SET PW ='888',TEL = '999' WHERE ID = 'ice';

DELETE FROM "MEMBER" WHERE ID = '100';

DELETE FROM "MEMBER" WHERE TEL = '011';
   
CREATE TABLE PRODUCT (
	ID VARCHAR2(200),
	NAME VARCHAR2(200),
	CONTENT VARCHAR2(200),
	PRICE NUMBER(38,0),
	COMPANY VARCHAR2(200),
	IMG VARCHAR2(200)
)

CREATE TABLE HEALTH (
	EXERCISE VARCHAR2(200),
	MET NUMBER(38,0)
)

SELECT * FROM MEMBER ORDER BY id -- 오름차순

SELECT * FROM MEMBER ORDER BY id DESC -- 내림차순

SELECT * FROM PRODUCT

--price로 내림차순 정렬하여 전체컬럼 검색
SELECT * FROM PRODUCT ORDER BY PRICE DESC

--company로 오름차순 정렬하여 제품의 이름, 내용, 가격 검색
SELECT NAME, CONTENT, PRICE FROM PRODUCT ORDER BY COMPANY

--id가 100인 제품의 이름과 가격 검색
SELECT NAME, PRICE FROM PRODUCT WHERE ID = '100'

--price가 5000인 제품명과 회사명
SELECT NAME, COMPANY FROM PRODUCT WHERE PRICE = 5000

--id가 100이고 가격이 1000인 제품명과 이미지 검색
SELECT NAME, IMG FROM PRODUCT WHERE ID = '100' AND PRICE = 1000

--회사명이 c100인 회사명과 제품명
SELECT COMPANY, NAME FROM PRODUCT WHERE COMPANY = 'c100'

--회사명이 c100, c200인 제품명과 가격
SELECT NAME, PRICE FROM PRODUCT WHERE COMPANY ='c100' OR COMPANY = 'c200'

--price가 5000원인 제품의 content를 품절로 수정
UPDATE PRODUCT SET CONTENT = '품절' WHERE PRICE = 5000

--id가 100, 102번 제품의 img를 o.png로, price를 10000으로 수정
UPDATE PRODUCT SET IMG = 'o.png', PRICE = 10000 WHERE ID = '100' OR ID ='102'

--id가 101번 제품의 company를 apple, name은 appleshoes로 수정
UPDATE PRODUCT SET COMPANY = 'apple', NAME = 'appleshoes' WHERE ID ='101' 

--name이 shoes1이거나 id가 107인 제품 삭제
DELETE FROM PRODUCT WHERE NAME = 'shoes1' OR ID = '107'

--회사명이 c100인 경우 모든 정보 삭제
DELETE FROM PRODUCT WHERE COMPANY = 'c100'

--테이블의 모든 정보 삭제
DELETE FROM PRODUCT

--테이블 삭제
DROP TABLE PRODUCT

   
   
   
   
   
   
   
   